Competition swerve
FRC9015/Crescendo pull request #42
Opened 2024-02-12 23:21 UTC by moyales

2024-02-13 03:48 UTC, lazychino requested changes
Can you update the PR description with the purpose of these changes?
Also are these changes tested with the Robot?

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/Swerve/SwerveSubsystem.java
> +                    return alliance.filter(value -> value == DriverStation.Alliance.Red).isPresent();
The original code is more readable.
This is twice in the same file it can be a helper method

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/Constants/Constants.java
> +import static frc.robot.Constants.Constants.SwervePIDControllerConstants.*;
Dont use `import .*` on new code import the constant you are using.

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/Constants/SwerveModuleConfiguration.java
> +	NW(31, 21, 11, 0), //TODO Change this ID Back to 15 on The Robot and Update it Here
Have the IDs been update to this? if so please removed the TODO comment

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/commands/DefaultDrive.java
> +	SlewRateLimiter xVelocityFilter = new SlewRateLimiter(driveSlewRateLimit);
Please use `SwerveConstants.driveSlewRateLimit`
Dont use .* that is a bad practice on Java

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +import com.revrobotics.CANSparkFlex;
Why is this being done? is not documented in the commits. Please add to the PR description

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +        double motorSpeed = 0.4;
final

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/LEDSubsystem.java
> +private final AddressableLED lED = new AddressableLED(0);//port number needs to be changed
`lED` reads weirds please use `led`

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/LEDSubsystem.java
> +private final AddressableLEDBuffer lEDBuffer = new AddressableLEDBuffer(1);//port number needs to be changed
same `lEDBuffer -> ledBuffer`

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/LimelightInterface.java
> +
remove extra new lines

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/PoseEstimator.java
> +    private SwerveDrivePoseEstimator swerveDrivePoseEstimator;
all of these should be final

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/Swerve/SwerveModule.java
> +        double kV = 3;
what this 3 means?

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/Swerve/SwerveSubsystem.java
> +                return alliance.filter(value -> value == DriverStation.Alliance.Red).isPresent();
The original code is more readable.

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/Swerve/SwerveSubsystem.java
> +                    return alliance.filter(value -> value == DriverStation.Alliance.Red).isPresent();
same as above

2024-02-13 03:48 UTC, lazychino commented on src/main/java/frc/robot/subsystems/Swerve/SwerveSubsystem.java
> +		//if statement is so that the teleop won't run if the Self Drive is on.
There is no `if` in this code, please remove comment

2024-02-17 21:41 UTC, closed without merging

2024-02-17 21:41 UTC, REVSIX commented
We are using yagsl, so this code is no longer what will be merged to main